version: "3"
services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    volumes:
      - ./docker/mongo/db:/data/db
      - ./docker/mongo/log/:/var/log/mongodb/
    ports:
      - "27017:27017"

  api:
    container_name: api_nodejs
    image: node:13
    working_dir: /home/node/api
    user: node
    environment:
      MONGO_URL: mongodb://mongo:27017/node_api
    volumes:
      - ./api:/home/node/api
    ports:
      - "8000:8000"
    command: ./wait-for-it mongo:27017 -- npm run dev
